import { Client, Service, Appointment, Barber, WorkingHours } from './types'

export const mockBarber: Barber = {
  id: '1',
  name: 'Carlos Silva',
  email: 'carlos@barberpro.com',
  phone: '(11) 99999-9999',
  shopName: 'Barbearia Elite',
  address: 'Rua das Flores, 123 - Centro',
}

export const mockServices: Service[] = [
  { id: '1', name: 'Corte Masculino', duration: 30, price: 45, active: true },
  { id: '2', name: 'Barba', duration: 20, price: 30, active: true },
  { id: '3', name: 'Corte + Barba', duration: 45, price: 65, active: true },
  { id: '4', name: 'Corte Infantil', duration: 25, price: 35, active: true },
  { id: '5', name: 'Pigmentação', duration: 60, price: 80, active: true },
  { id: '6', name: 'Hidratação', duration: 30, price: 40, active: false },
]

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'João Pedro Santos',
    phone: '(11) 98765-4321',
    email: 'joao@email.com',
    birthDate: '1990-05-15',
    createdAt: '2024-01-10',
    totalVisits: 12,
    lastVisit: '2025-05-02',
    favoriteService: 'Corte + Barba',
  },
  {
    id: '2',
    name: 'Rafael Oliveira',
    phone: '(11) 91234-5678',
    email: 'rafael@email.com',
    createdAt: '2024-02-20',
    totalVisits: 8,
    lastVisit: '2025-05-05',
    favoriteService: 'Corte Masculino',
  },
  {
    id: '3',
    name: 'Lucas Mendes',
    phone: '(11) 99876-5432',
    createdAt: '2024-03-15',
    totalVisits: 5,
    lastVisit: '2025-04-28',
    favoriteService: 'Barba',
  },
  {
    id: '4',
    name: 'Fernando Costa',
    phone: '(11) 92345-6789',
    email: 'fernando@email.com',
    birthDate: '1985-11-22',
    notes: 'Prefere corte mais curto nas laterais',
    createdAt: '2024-04-01',
    totalVisits: 15,
    lastVisit: '2025-05-08',
    favoriteService: 'Corte Masculino',
  },
  {
    id: '5',
    name: 'André Lima',
    phone: '(11) 93456-7890',
    createdAt: '2024-05-10',
    totalVisits: 3,
    lastVisit: '2025-04-20',
    favoriteService: 'Corte + Barba',
  },
  {
    id: '6',
    name: 'Thiago Souza',
    phone: '(11) 94567-8901',
    email: 'thiago@email.com',
    createdAt: '2024-06-05',
    totalVisits: 7,
    lastVisit: '2025-05-07',
    favoriteService: 'Pigmentação',
  },
]

const today = new Date()
const formatDate = (date: Date) => date.toISOString().split('T')[0]

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    clientId: '1',
    client: mockClients[0],
    serviceId: '3',
    service: mockServices[2],
    date: formatDate(today),
    time: '09:00',
    status: 'confirmado',
    createdAt: '2025-05-07',
  },
  {
    id: '2',
    clientId: '2',
    client: mockClients[1],
    serviceId: '1',
    service: mockServices[0],
    date: formatDate(today),
    time: '10:00',
    status: 'confirmado',
    createdAt: '2025-05-06',
  },
  {
    id: '3',
    clientId: '4',
    client: mockClients[3],
    serviceId: '1',
    service: mockServices[0],
    date: formatDate(today),
    time: '11:00',
    status: 'concluido',
    createdAt: '2025-05-05',
  },
  {
    id: '4',
    clientId: '6',
    client: mockClients[5],
    serviceId: '5',
    service: mockServices[4],
    date: formatDate(today),
    time: '14:00',
    status: 'confirmado',
    createdAt: '2025-05-08',
  },
  {
    id: '5',
    clientId: '3',
    client: mockClients[2],
    serviceId: '2',
    service: mockServices[1],
    date: formatDate(today),
    time: '15:30',
    status: 'pendente',
    createdAt: '2025-05-08',
  },
  {
    id: '6',
    clientId: '5',
    client: mockClients[4],
    serviceId: '3',
    service: mockServices[2],
    date: formatDate(new Date(today.getTime() + 86400000)),
    time: '10:00',
    status: 'confirmado',
    createdAt: '2025-05-07',
  },
  {
    id: '7',
    clientId: '1',
    client: mockClients[0],
    serviceId: '2',
    service: mockServices[1],
    date: formatDate(new Date(today.getTime() + 86400000 * 2)),
    time: '11:30',
    status: 'confirmado',
    createdAt: '2025-05-08',
  },
]

export const mockWorkingHours: WorkingHours[] = [
  { day: 0, active: false, start: '09:00', end: '18:00' },
  { day: 1, active: true, start: '09:00', end: '19:00' },
  { day: 2, active: true, start: '09:00', end: '19:00' },
  { day: 3, active: true, start: '09:00', end: '19:00' },
  { day: 4, active: true, start: '09:00', end: '19:00' },
  { day: 5, active: true, start: '09:00', end: '20:00' },
  { day: 6, active: true, start: '08:00', end: '17:00' },
]
